name: Auto PR Creation Caller

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - 'support/*.*.*'
      - 'support/*.*.*.*'
      - feature/CMF-14020

jobs:
  call_auto_pr_workflow:
    uses: rdkcentral/build_tools_workflows/.github/workflows/auto_pr_creation_rpi_manifests.yml@feature/CMF-14020
    secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
